Reverted removal of StreamingContext from the OnDeserialized method.
The OnDeserialized method requires a StreamingContext parameter.

Attempting to use the WCF profiler was throwing the following exception:

System.Runtime.Serialization.InvalidDataContractException: Serialization
Callback 'Void OnDeserialized()' in type
'StackExchange.Profiling.MiniProfiler' must have a single parameter of
type 'System.Runtime.Serialization.StreamingContext'.